#!/bin/bash

hash docker 2>/dev/null || {
  yum install -y yum-utils device-mapper-persistent-data lvm2
  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  yum makecache fast
  yum install -y docker-ce
  yum install -y epel-release
  yum install -y python-pip
  pip install docker-compose
  yum upgrade -y python*
  systemctl enable docker
  systemctl start docker
  usermod -aG docker vagrant
} > /dev/null 2>&1