#!/bin/bash

hash mysql 2>/dev/null || {
  dnf module install mariadb -y
  echo "bind-address=0.0.0.0" >> /etc/my.cnf.d/mariadb-server.cnf
  systemctl enable --now mariadb
  mysql -uroot -e 'USE mysql; UPDATE `user` SET `Host`="%" WHERE `User`="root" AND `Host`="localhost"; DELETE FROM `user` WHERE `Host` != "%" AND `User`="root"; FLUSH PRIVILEGES;'
  mysql -uroot -e 'USE mysql; UPDATE `user` SET `password`=PASSWORD("") WHERE User="root";'
} > /dev/null 2>&1



