#!/bin/bash

systemctl mask firewalld > /dev/null 2>&1
systemctl stop firewalld > /dev/null 2>&1

hash require 2>/dev/null || {
  curl --fail --silent --show-error https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/require --output /usr/bin/require
  chmod +x /usr/bin/require
}

require jq,git,vim
