#!/bin/bash

hash phantomjs 2>/dev/null || {
  yum install -y fontconfig freetype freetype-devel fontconfig-devel libstdc++
  cd /tmp
  wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  mkdir -p /opt/phantomjs
  tar -xjvf phantomjs-2.1.1-linux-x86_64.tar.bz2 --strip-components=1 -C /opt/phantomjs/
  ln -s /opt/phantomjs/bin/phantomjs /usr/bin/phantomjs
} > /dev/null 2>&1
