#!/bin/bash

hash psql 2>/dev/null || {
  dnf install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm -y
  dnf module disable postgresql -qy
  dnf install postgresql12 postgresql12-server postgresql-contrib -y
  /usr/pgsql-12/bin/postgresql-12-setup initdb
  echo "listen_addresses = '*'" >> /var/lib/pgsql/12/data/postgresql.conf
  echo "host all all 0.0.0.0/0 trust" >> /var/lib/pgsql/12/data/pg_hba.conf
  sed -i "s/peer/trust/g" /var/lib/pgsql/12/data/pg_hba.conf
  sed -i "s/ident/trust/g" /var/lib/pgsql/12/data/pg_hba.conf
  systemctl enable --now postgresql-12
  sudo -u postgres psql 2>/dev/null -c "alter user postgres with password 'vagrant'" > /dev/null 2>&1
  sudo -u postgres createuser -s vagrant > /dev/null 2>&1
} > /dev/null 2>&1
