#!/bin/bash

apt-get update

hash git 2>/dev/null || {
  apt-get install git -y
} > /dev/null 2>&1

hash require 2>/dev/null || {
  curl --fail --silent --show-error https://raw.githubusercontent.com/stfnhh/vagrant-provisioning-scripts/master/ubuntu/require --output /usr/bin/require
  chmod +x /usr/bin/require
}
