#!/bin/bash

hash pip3 2>/dev/null || {
  apt-get install python3-pip libpng-dev gcc -y
  alias pip=$(which pip3)
  echo "alias pip=$(which pip3)" >> /etc/bashrc
  echo "alias pip=$(which pip3)" >> /home/vagrant/.bashrc
  echo "alias pip=$(which pip3)" >> /root/.bashrc
  pip3 install virtualenv
} > /dev/null 2>&1